services:
  - type: web
    name: chatvot-elearning
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_MY_APP_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
